<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TimeSeries.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TimeSeries.NET\TimeSeries.NET.csproj" />
    <ProjectReference Include="..\..\src\TimeSeries.NET.Data\TimeSeries.NET.Data.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

</Project>
